[package]
name = "rs-partyplayer"
version = "0.1.0"
authors = ["Rink Springer <rink@rink.nu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
rust-ini = "0.13.0"
tiny_http = "0.6"
